service: sahara-ansh
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  memorySize: 10240

  region: "ap-south-1"
  deploymentBucket:
    name: ${env:SERVERLESS_DEPLOYMENT_BUCKET}
  stage: ${opt:stage}
  tags:
    project: 'sahara-ansh'
    environment: ${opt:stage}
    createdBy: 'serverless-codedeploy'
  
  apiGateway:
    apiKeys: ${self:custom.apiKeys.${opt:stage}}

  iamRoleStatements:  
    # Statement for Amazon S3 Full Access
    - Effect: "Allow"
      Action: 
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource:
            - !Sub arn:aws:s3:::${env:S3_BUCKET_NAME}
            - !Sub arn:aws:s3:::${env:S3_BUCKET_NAME}/*

    # Statement for Amazon SageMaker Full Access
    - Effect: "Allow"
      Action: 
        - sagemaker:InvokeEndpoint
      Resource: "*"

    # Statement for AWS Lambda Full Access
    - Effect: "Allow"
      Action: 
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!.venv/**'
    - '!infra/**'
    - '!scripts/**'
    - '!test/**'
    - '!tests-integration'
    - '!adityaenv/**'
    - '!backendenv/**'


plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-dotenv-plugin


custom:
 wsgi:
   app: src/main.app
   packRequirements: false
 prune:
   automatic: true
   includeLayers: true
   number: 5
 vpc:
    securityGroupIds:
      - ${env:VPC_SECURITY_GROUP}
    subnetIds:
      - ${env:VPC_SUBNET_ID_1}
      - ${env:VPC_SUBNET_ID_2}

 apiKeys:
    dev:
      - sahara-ansh-dev
    uat:
      - sahara-ansh-uat
    release:
      - sahara-ansh-release
functions:
  singlePdfS3UploadHandler:
    handler: src/lambdas/pdf_monitoring_lambda.lambda_handler
    timeout: 900
    events:
      - s3:
          bucket: ${env:S3_BUCKET_NAME}
          event : s3:ObjectCreated:*
          rules : 
            - prefix : ${env:S3_SAVE_INPUT_BUCKET}
            
          existing: true
      

  app:
    handler: wsgi_handler.handler
    timeout: 30
    vpc: ${self:custom.vpc}
    events:
     - http:
          path: /{any+}
          method: ANY
          private: true
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - X-Auth-Token
  
