import json

import aws_cdk.aws_secretsmanager as secretsmanager

from config import (
	APP_NAME, STAGE, DEPLOYMENT_BUCKET,
	AWS_TAG_PROJECT_NAME, AWS_TAG_CREATED_BY,
	DEBUG,
	STAGE,
	REGION,
	S3_BUCKET_NAME,
	S3_SAVE_INPUT_BUCKET,
	SAGEMAKER_ENDPOINT,
	SERVERLESS_DEPLOYMENT_BUCKET,
	S3_EMBEDDINGS_PATH,
	EMBEDDINGS_ENDPOINT,
	VPC_SUBNET_ID_2,
	VPC_SUBNET_ID_1,
	VPC_SECURITY_GROUP,
	ANUBHAV_EMBEDDINGS
)


def create_secrets(scope):

	secret_value = {
		'PYTHON_ENV': STAGE,
		'LOG_LEVEL': 'INFO',
		'AWS_TAG_PROJECT_NAME': AWS_TAG_PROJECT_NAME,
		'AWS_TAG_CREATED_BY': AWS_TAG_CREATED_BY,

		'DEPLOYMENT_BUCKET': DEPLOYMENT_BUCKET,
		'BUILD_ENV': STAGE,
		'DEBUG': DEBUG,
		'REGION': REGION,
		'S3_BUCKET_NAME': S3_BUCKET_NAME,
		'S3_SAVE_INPUT_BUCKET': S3_SAVE_INPUT_BUCKET,
		'SAGEMAKER_ENDPOINT': SAGEMAKER_ENDPOINT,
		'SERVERLESS_DEPLOYMENT_BUCKET': SERVERLESS_DEPLOYMENT_BUCKET,
		'S3_EMBEDDINGS_PATH': S3_EMBEDDINGS_PATH,
		'EMBEDDINGS_ENDPOINT': EMBEDDINGS_ENDPOINT,
		'VPC_SUBNET_ID_2': VPC_SUBNET_ID_2,
		'VPC_SUBNET_ID_1':VPC_SUBNET_ID_1,
		'VPC_SECURITY_GROUP':VPC_SECURITY_GROUP,
		'ANUBHAV_EMBEDDINGS' :ANUBHAV_EMBEDDINGS

	}

	secret_name = f"{APP_NAME}-secret"
	secret = secretsmanager.Secret(scope, secret_name,
		secret_name=secret_name,
    	generate_secret_string = secretsmanager.SecretStringGenerator(
        	secret_string_template= json.dumps(secret_value),
        	generate_string_key="password"
    	)
	)
	return secret
